{% set name = "pylibscrypt" %}
{% set version = "2.0.0" %}
{% set sha256 = "5afffc2cf056de86a000c13627ddca87fac14380939694aa6fbf4875926c0146" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - openssl                      # [not win]
    - scrypt
  run:
    - openssl                      # [not win]
    - python
    - scrypt
    - libsodium

test:
  imports:
    - pylibscrypt
  commands:
    - python -m pylibscrypt.tests                    # [not osx]
    - python -m pylibscrypt.pylibsodium              # [not osx]
    - python -m pylibscrypt.pbkdf2                   # [not osx]

about:
  home: https://github.com/jvarho/pylibscrypt
  license: ISC
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  dev_url: https://github.com/jvarho/pylibscrypt
  doc_url: https://github.com/jvarho/pylibscrypt
  summary: 'Scrypt for Python'

extra:
  recipe-maintainers:
    - holgern
