travis:
  secure:
    BINSTAR_TOKEN: mcNrJ1IBpb4ef01Eb+nSKHz36WM53lFWGpVOofdpWiX8VPaAIioyJBiCOtWBmsE2ZcovrpTh4ilBgoj/Hgcl3T1chBxZxyP+YX5f18L3bYbmNtavPeLce3Yd2gP2L80FcB2K/3te8AhsnIHx40B1NZgfIofvF0onAbdCKwMvoNEKMm1Qdzhl8LKUu8Hz73aaawBdJLwBtfbkolLmH92tWUMyJBbaNkNdGBn32lxqyXEYo99oIm4GcfIMO0ga3Y1kM+8yRkm+qYtcLE4EBBloefDgrQ+/MDQn8xkJ3h7meUsoGsdAYj093dS+MwTLJVi07LZJ8TTs6A5gzrjFWtiLEYBeBdHpu39vBmepPWDfxa5xxUW2vLRWGb/kKIxjKZyRM82hMOBkZ6xs4f+NZc5CNrddh6p30ORCRz3c+Wj2EqZpIQZp+VxhI9iYdxtL3WJRFtuM3v4uYYQGDqIEegqZta1wNQZeDbT2hyDxBy/rRL7xFcriWzBvazVvzs1gMx709AIQXYJUQ0IZfUJZnxiHy1lEuMTdlpbuAC2KF+8wk6MbD6PS6r02x/vIk+2gQz2Bdk4GE9jn2g9cL/ooB4PFySZg+KD505sBRzftZVZMlbaWuaGxEHv73VZBxGNSNuT7uVdrbd7dXUqeodD0HgKRNDL1YNkHDx8Rtoi0tKZU2M4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
