travis:
  secure:
    BINSTAR_TOKEN: H/WDrtaXC2EkmagKxlXl+2RG89plnDgqLHfMLRzTNIfn/K5zGygogWOQ/aUM1T86HZUTSybkqgljQmUzoX4jlW+g0QqmFUOQp7mTDZmP/GhoVdipDD37YvctBDiKL0/5sSZhzvA70lTi61TQ/BuJnw3snatAyjMAaKR1rGex3T5AQ4Aop58kpavMY+qllW9fy8hUN1eTbQHaGEnvdkliogaJpmg9g95doGRwMu/yg/nb+ddu3YAgZjZY15fG2j8LAb8m/1SZZqMlf7G7xBANB/rFELHE6RdFEiE4tLe520repJ+iWZxM2hUS//pd26ElsLDb7Q98C57Li612eXGnlhISee3IpKqZvMuUOiRIBX9ekk1Qmlb0+NPEbXIzQhFUFhLSHHKKVQdyTXc9KqoLpYBxXFzGqnFyNpBAj11nMolZcvYnsA+XFtBUa47Z/UOAZM3ZOsWCfyYRazw/JqhpFzU7MVJzFyWokHqpU75PKzXs5rgMRVREhc86RvpKpjoKFzehviZpz7RI2g01Hy8V/hnOpn7mQjNT1amFnHBLSqRHKcXNhNfSrVG8yKzAxuk7AYCA7NRGJO0PUPUs3VEeqzDVOQezAwIb0W/FDwKxnS9azhHdbfd7OE7ngI3hhkrP4cASwnCpaaUU94r0/InOYibIRwVZ1+e/YiQIFKg/55Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
